### ISSUE TITLE
Regression in 0.10.0: readTimed is not a function

### ISSUE THREAD

**Issue by parkan** [libp2p/js-libp2p-spdy#44]
Not really sure how to diagnose this, but we're seeing a regression in 0.10 (see trace below)

~~In a different test, some logic incorrectly appears to execute multiple times and/or some callbacks are called repeatedly -- hard to make much of the mocha output in the async scenario~~ [EDIT: this appears to be a separate breaking change in js-libp2p-swarm v0.26.0]

Had to pin to 0.9.0 for the moment, let me know how I can help diagnose. The only place that this hits our code is here: https://github.com/mediachain/aleph/blob/master/src/peer/node.js#L143

```
     Uncaught TypeError: readTimed is not a function
      at more (node_modules/pull-reader/index.js:55:7)
      at reader (node_modules/pull-reader/index.js:74:5)
      at node_modules/pull-length-prefixed/lib/decode.js:23:5
      at pull (node_modules/pull-stream/pull.js:41:14)
      at node_modules/pull-stream/pull.js:22:22
      at pull (node_modules/pull-stream/pull.js:41:14)
      at MediachainNode.pingHandler (src/peer/node.js:144:5)
      at matcher (node_modules/multistream-select/src/listener/select-handler.js:40:28)
      at some (node_modules/multistream-select/src/listener/select-handler.js:71:7)
      at done (node_modules/multistream-select/node_modules/async/internal/createTester.js:22:17)
      at node_modules/multistream-select/node_modules/async/internal/once.js:12:16
      at iteratorCallback (node_modules/multistream-select/node_modules/async/eachOf.js:52:13)
      at node_modules/multistream-select/node_modules/async/internal/onlyOnce.js:12:16
      at node_modules/multistream-select/node_modules/async/internal/createTester.js:35:21
      at handlers.(anonymous function).matchFunc (node_modules/multistream-select/src/listener/select-handler.js:64:9)
      at Object.matchExact [as matchFunc] (node_modules/multistream-select/src/listener/match-exact.js:5:3)
      at some (node_modules/multistream-select/src/listener/select-handler.js:57:20)
      at wrappedIteratee (node_modules/multistream-select/node_modules/async/internal/createTester.js:27:13)
      at eachOfArrayLike (node_modules/multistream-select/node_modules/async/eachOf.js:57:9)
      at exports.default (node_modules/multistream-select/node_modules/async/eachOf.js:9:5)
      at node_modules/multistream-select/node_modules/async/internal/createTester.js:46:13
      at matcher (node_modules/multistream-select/src/listener/select-handler.js:55:3)
      at lp.decodeFromReader (node_modules/multistream-select/src/listener/select-handler.js:29:7)
      at node_modules/pull-length-prefixed/lib/decode.js:93:9
      at Object.cb (node_modules/pull-length-prefixed/lib/decode.js:105:5)
      at drain (node_modules/pull-reader/index.js:39:14)
      at more (node_modules/pull-reader/index.js:51:13)
      at Object.reader.read (node_modules/pull-reader/index.js:95:7)
      at readMessage (node_modules/pull-length-prefixed/lib/decode.js:100:10)
      at Object.cb (node_modules/pull-length-prefixed/lib/decode.js:86:7)
      at drain (node_modules/pull-reader/index.js:39:14)
      at more (node_modules/pull-reader/index.js:51:13)
      at node_modules/pull-reader/index.js:62:9
      at node_modules/pull-reader/index.js:20:7
      at node_modules/pull-reader/index.js:110:13
      at drain (node_modules/stream-to-pull-stream/index.js:141:18)
      at Stream.<anonymous> (node_modules/stream-to-pull-stream/index.js:150:5)
      at readableAddChunk (node_modules/readable-stream/lib/_stream_readable.js:198:18)
      at Stream.Readable.push (node_modules/readable-stream/lib/_stream_readable.js:157:10)
      at Stream._handleData (node_modules/spdy-transport/lib/spdy-transport/stream.js:275:8)
      at Stream._handleFrame (node_modules/spdy-transport/lib/spdy-transport/stream.js:122:10)
      at Connection._handleFrame (node_modules/spdy-transport/lib/spdy-transport/connection.js:326:12)
      at Parser.<anonymous> (node_modules/spdy-transport/lib/spdy-transport/connection.js:158:10)
      at readableAddChunk (node_modules/readable-stream/lib/_stream_readable.js:198:18)
      at Parser.Readable.push (node_modules/readable-stream/lib/_stream_readable.js:157:10)
      at Parser.Transform.push (node_modules/readable-stream/lib/_stream_transform.js:123:32)
      at next (node_modules/spdy-transport/lib/spdy-transport/protocol/base/parser.js:52:12)
      at node_modules/spdy-transport/lib/spdy-transport/protocol/spdy/parser.js:57:5
      at Parser.onFrameBody (node_modules/spdy-transport/lib/spdy-transport/protocol/spdy/parser.js:128:12)
      at Parser.execute (node_modules/spdy-transport/lib/spdy-transport/protocol/spdy/parser.js:50:8)
      at Parser._consume (node_modules/spdy-transport/lib/spdy-transport/protocol/base/parser.js:92:8)
      at node_modules/spdy-transport/lib/spdy-transport/protocol/base/parser.js:60:12
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by diasdavid** [comment]
@parkan can I get an `npm ls`? Or even better can you run [ncu](http://npmjs.org/npm-check-updates) on the project? We updated every single module with the [Async Crypto PR](https://github.com/ipfs/js-ipfs/pull/485) and I do not recommend to use a mix of old and new modules.

**Comment by parkan** [comment]
We've updated most of the dependencies, minus `libp2p-swarm` because of [this breaking API change](https://github.com/libp2p/js-libp2p-swarm/commit/c199bfcba51f3fec5f7ba80c50f8c245b0901887#commitcomment-19792372). Let me try next-version to see if we're still breaking.

**Comment by parkan** [comment]
Updated everything else across the board, back to green! Seems like possibly secio or pull-stream change? Either way, closing.
